#############################################################################
# Generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#  Feb 21, 2021 11:09:55 PM CST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -takefocus 1 
    wm focusmodel $top passive
    wm geometry $top 600x600+288+143
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 600 1422
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Editor de líneas de reporte"
    vTcl:DefineAlias "$top" "MainWindow" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    button $top.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command ReplaceButton_Click \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Reemplazar 
    vTcl:DefineAlias "$top.but48" "btnReplace" vTcl:WidgetProc "MainWindow" 1
    labelframe $top.lab47 \
        -font TkDefaultFont -foreground black -text {Buscar: } \
        -background $vTcl(actual_gui_bg) -height 161 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 580 
    vTcl:DefineAlias "$top.lab47" "frmSearch" vTcl:WidgetProc "MainWindow" 1
    set site_3_0 $top.lab47
    radiobutton $site_3_0.rad48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -command SearchRadioButton_Selected -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Número de Línea} -value LineNumber \
        -variable searchOption 
    vTcl:DefineAlias "$site_3_0.rad48" "rdbLineNumber" vTcl:WidgetProc "MainWindow" 1
    entry $site_3_0.ent49 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -justify center -selectbackground blue \
        -selectforeground white -textvariable valTxtLineNumber \
        -validate focusout -validatecommand ValidateLineNumber -width 174 
    vTcl:DefineAlias "$site_3_0.ent49" "txtLineNumber" vTcl:WidgetProc "MainWindow" 1
    radiobutton $site_3_0.rad50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -command SearchRadioButton_Selected -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Contenido -value Content -variable searchOption 
    vTcl:DefineAlias "$site_3_0.rad50" "rdbLineContent" vTcl:WidgetProc "MainWindow" 1
    entry $site_3_0.ent51 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -state disabled \
        -textvariable valTxtLineContent -width 534 
    vTcl:DefineAlias "$site_3_0.ent51" "txtLineContent" vTcl:WidgetProc "MainWindow" 1
    button $site_3_0.but57 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command SearchButton_Click \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Buscar 
    vTcl:DefineAlias "$site_3_0.but57" "btnSearch" vTcl:WidgetProc "MainWindow" 1
    label $site_3_0.lab58 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground #ff0000 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -textvariable valLblErrors 
    vTcl:DefineAlias "$site_3_0.lab58" "lblErrors" vTcl:WidgetProc "MainWindow" 1
    label $site_3_0.lab45 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground #0000ff -text Label \
        -textvariable valLblMessages 
    vTcl:DefineAlias "$site_3_0.lab45" "lblMessages" vTcl:WidgetProc "MainWindow" 1
    place $site_3_0.rad48 \
        -in $site_3_0 -x 0 -relx 0.017 -y 0 -rely 0.109 -width 0 \
        -relwidth 0.297 -height 0 -relheight 0.163 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent49 \
        -in $site_3_0 -x 0 -relx 0.052 -y 0 -rely 0.323 -width 174 \
        -relwidth 0 -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad50 \
        -in $site_3_0 -x 0 -relx 0.017 -y 0 -rely 0.484 -width 0 \
        -relwidth 0.297 -height 0 -relheight 0.163 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent51 \
        -in $site_3_0 -x 0 -relx 0.052 -y 0 -rely 0.667 -width 534 \
        -relwidth 0 -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but57 \
        -in $site_3_0 -x 0 -relx 0.81 -y 0 -rely 0.272 -width 88 -relwidth 0 \
        -height 48 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab58 \
        -in $site_3_0 -x 0 -relx 0.379 -y 0 -rely 0.248 -width 0 \
        -relwidth 0.409 -height 0 -relheight 0.18 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 0 -relx 0.362 -y 0 -rely 0.497 -width 0 \
        -relwidth 0.426 -height 0 -relheight 0.143 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab53 \
        -font TkDefaultFont -foreground black -text {Resultados: } \
        -background $vTcl(actual_gui_bg) -height 165 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 580 
    vTcl:DefineAlias "$top.lab53" "frmResult" vTcl:WidgetProc "MainWindow" 1
    set site_3_0 $top.lab53
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_3_0.scr63 \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$site_3_0.scr63" "scrlListBox" vTcl:WidgetProc "MainWindow" 1

    $site_3_0.scr63.01 configure -background white \
        -cursor xterm \
        -disabledforeground #a3a3a3 \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #e1f0ff \
        -selectforeground white \
        -selectmode single \
        -state disabled \
        -width 10 \
        -listvariable valLstLines
    place $site_3_0.scr63 \
        -in $site_3_0 -x 0 -relx 0.017 -y 0 -rely 0.136 -width 0 \
        -relwidth 0.967 -height 0 -relheight 0.805 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab55 \
        -font TkDefaultFont -foreground black -text {Reempazar: } \
        -background $vTcl(actual_gui_bg) -height 51 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 580 
    vTcl:DefineAlias "$top.lab55" "frmReplace" vTcl:WidgetProc "MainWindow" 1
    set site_3_0 $top.lab55
    entry $site_3_0.ent56 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable valTxtReplaceLine -width 554 
    vTcl:DefineAlias "$site_3_0.ent56" "txtReplace" vTcl:WidgetProc "MainWindow" 1
    place $site_3_0.ent56 \
        -in $site_3_0 -x 0 -relx 0.017 -y 0 -rely 0.423 -width 554 \
        -relwidth 0 -height 21 -relheight 0 -anchor nw -bordermode ignore 
    labelframe $top.lab59 \
        -font TkDefaultFont -foreground black -text Archivo: \
        -background $vTcl(actual_gui_bg) -height 65 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 580 
    vTcl:DefineAlias "$top.lab59" "frmFile" vTcl:WidgetProc "MainWindow" 1
    set site_3_0 $top.lab59
    label $site_3_0.lab60 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {<= Abrir archivo} -textvariable valFileName 
    vTcl:DefineAlias "$site_3_0.lab60" "lblFileName" vTcl:WidgetProc "MainWindow" 1
    button $site_3_0.but61 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command BtnOpenFile_Click \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Archivo 
    vTcl:DefineAlias "$site_3_0.but61" "btnOpenFile" vTcl:WidgetProc "MainWindow" 1
    place $site_3_0.lab60 \
        -in $site_3_0 -x 0 -relx 0.19 -y 0 -rely 0.462 -width 0 \
        -relwidth 0.788 -height 0 -relheight 0.354 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but61 \
        -in $site_3_0 -x 0 -relx 0.017 -y 0 -rely 0.462 -width 68 -relwidth 0 \
        -height 28 -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but48 \
        -in $top -x 0 -relx 0.383 -y 0 -rely 0.9 -width 118 -relwidth 0 \
        -height 38 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.122 -width 0 -relwidth 0.967 \
        -height 0 -relheight 0.268 -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.4 -width 0 -relwidth 0.967 \
        -height 0 -relheight 0.368 -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.78 -width 0 -relwidth 0.967 \
        -height 0 -relheight 0.104 -anchor nw -bordermode ignore 
    place $top.lab59 \
        -in $top -x 0 -relx 0.017 -y 0 -width 0 -relwidth 0.967 -height 0 \
        -relheight 0.108 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

